name: Fetch Data and Save as JSON

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Run the workflow weekly at 00:00

jobs:
  fetch_and_save_data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch data and save as JSON
        run: |
          python -c "import requests; response = requests.get('https://myhome-apply.vercel.app/api/home/getInfo?category=APT&s_date=2023-03-01&e_date=2023-03-31'); data = response.json(); open('data.json', 'w').write(response.text)"

      - name: Commit and push changes
        run: |
          git config --global user.name "rumblekat"
          git config --global user.email "reki318@naver.com"
          git add data.json
          git commit -m "Update data.json with latest data" || exit 0
          git push
